### PR TITLE
Add inrupt.net as a provider

### PR DESCRIPTION
**Pull request by RubenVerborgh**
Untested.

### CODE REVIEW

**Comment by melvincarvalho** [comment]
Looks good.  Minor comments.

This change is doing more than one thing : 

1. Changing existing provider images
2. Adding inrupt as a provider

For the first part should we put some images inline, to protect user privacy?  Otherwise all pods will see the ip addresses of all new sign ups.

For the 2nd part, should there be a transparent policy on how new entries are listed e.g. (first in first out, or highest rated, random, at inrupt's discretion).  Otherwise we might get commit wars with new pod providers trying to gain advantage over each other.

**Comment by RubenVerborgh** [comment]
> This change is doing more than one thing :
> 
>     1. Changing existing provider images
> 
>     2. Adding inrupt as a provider

Yeah, both combined are reply to @timbl's "fix this" 😄 

> For the first part should we put some images inline, to protect user privacy? Otherwise all pods will see the ip addresses of all new sign ups.

Well, this is an improvement already, databox.me would ask for certs so could also know who you are. So given that we don't make things worse, I would consider this a separate issue.

> For the 2nd part, should there be a transparent policy on how new entries are listed e.g. (first in first out, or highest rated, random, at inrupt's discretion).

This is just a data document; actual selection (and "recommended" flag) is done by an app somewhere.

**Comment by melvincarvalho** [comment]
Good points!  We can open a separate issue to inline images.

**Comment by timbl** [comment]
Process for deciding who gets in which lists is an important much longer topic.  But now both taking out databix and putting inrupt seem to be clearly indicated. We can certainly add more without having to roll others off. If nec makinv the ui diff.  But another issue

**Pull request merged**
